vendinginspection/VendingInspection/VendingInspection/Controllers/MachineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VendingInspection.Models;
using VendingInspection.ViewModels;
using System.Web.Script.Serialization;

namespace VendingInspection.Controllers
{
    public class MachineController : Controller
    {
        private VendingCareEntities db = new VendingCareEntities();

        #region Method and Functions related to Web Service

        


        #endregion



        [HttpPost]
        public JsonResult GetMachineDetailsFromBarcode(string barcode)
        {
            try
            {
                var machine = db.GetMachineFromBarCode(barcode).SingleOrDefault();
               
                if (machine != null)
                {
                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    string result = serializer.Serialize(machine);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }

            return null;
        }


        //
        // GET: /Machine/

        public ActionResult Index()
        {
            IEnumerable<MachineViewModel> model = null;
            model = (IEnumerable<MachineViewModel>)(from machine in db.Machines
                                                     join machinetechnicianLink in db.MachineTechnicianLinks
                                                    on machine.MachineId equals machinetechnicianLink.MachineId
                                                    join user in db.UserDetails on machinetechnicianLink.UserDetailId equals user.UserDetailId
                                                    join machinerslink in db.MachineRSLinks
                                                    on machine.MachineId equals machinerslink.MachineId
                                                    join rs in db.RSDetails on  machinerslink.RSId equals rs.RSId
                                                    select new
                                                    {
                                                        MachineId = machinetechnicianLink.MachineId,
                                                        TechnicianName = user.FirstName + " " + user.LastName,
                                                        BarCode = machine.Barcode,
                                                        CustomerName = machine.CustomerName,
                                                        Active = machine.IsActive,
                                                        RSName = rs.RSName,
                                                        CustomerAddress = machine.CustomerAddress
                                                    }).ToList().ToNonAnonymousList(typeof(MachineViewModel));

            
            return View(model);
        }

        //
        // GET: /Machine/Details/5

        public ActionResult Details(int id = 0)
        {
            Machine machine = db.Machines.Single(m => m.MachineId == id);
            if (machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        //
        // GET: /Machine/Create

        public ActionResult Create()
        {
            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(), "UserDetailId", "FirstName");
            ViewBag.Brands = new SelectList(db.Brands, "BrandId", "BrandName");
            ViewBag.Models = new SelectList(db.Models, "ModelId", "ModelName");
            ViewBag.WaterSources = new SelectList(db.WaterSources, "WaterSourceId", "WaterSourceName");
            ViewBag.Manufacturers = new SelectList(db.Manufacturers, "MfgrId", "MfgrName");
            ViewBag.AccountClasses = new SelectList(db.AccountClasses, "AccountClassId", "AccountClassName");
            ViewBag.RS = new SelectList(db.RSDetails, "RSId", "RSName");
            return View();
        }

        //
        // POST: /Machine/Create

        [HttpPost]
        public ActionResult Create(Machine machine, Int64 Technician, Int32 RS)
        {
            if (ModelState.IsValid)
            {
                db.Machines.AddObject(machine);
                db.SaveChanges();

                var machineTechLink = new MachineTechnicianLink();
                machineTechLink.MachineId = machine.MachineId;
                machineTechLink.UserDetailId = Technician;
                db.MachineTechnicianLinks.AddObject(machineTechLink);
                db.SaveChanges();

                var machineRSLink = new MachineRSLink();
                machineRSLink.MachineId = machine.MachineId;
                machineRSLink.RSId = RS;
                db.MachineRSLinks.AddObject(machineRSLink);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(machine);
        }

        //
        // GET: /Machine/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Machine machine = db.Machines.Single(m => m.MachineId == id);

            var technicianId = db.MachineTechnicianLinks.Where(m => m.MachineId == machine.MachineId).SingleOrDefault().UserDetailId;
            var rsId = db.MachineRSLinks.Where(m => m.MachineId == machine.MachineId).SingleOrDefault().RSId;

            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(),"UserDetailId", "FirstName", technicianId);
            ViewBag.Brands = new SelectList(db.Brands, "BrandName", "BrandName");
            ViewBag.Models = new SelectList(db.Models, "ModelName", "ModelName");
            ViewBag.WaterSources = new SelectList(db.WaterSources, "WaterSourceName", "WaterSourceName");
            ViewBag.Manufacturers = new SelectList(db.Manufacturers, "MfgrName", "MfgrName");
            ViewBag.AccountClasses = new SelectList(db.AccountClasses, "AccountClassName", "AccountClassName");
            ViewBag.RSDetails = new SelectList(db.RSDetails,"RSId", "RSName", rsId);
            if (machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        //
        // POST: /Machine/Edit/5

        [HttpPost]
        public ActionResult Edit(Machine machine, Int64 Technician, Int32 RSName)
        {
            if (ModelState.IsValid)
            {
                db.Machines.Attach(machine);
                db.ObjectStateManager.ChangeObjectState(machine, EntityState.Modified);
                db.SaveChanges();

                var machineTechLink = db.MachineTechnicianLinks.Where(m => m.MachineId == machine.MachineId).SingleOrDefault();
                machineTechLink.UserDetailId = Technician;
                db.ObjectStateManager.ChangeObjectState(machineTechLink, EntityState.Modified);
                db.SaveChanges();

                var machineRSLink = db.MachineRSLinks.Where(m => m.MachineId == machine.MachineId).SingleOrDefault();
                machineRSLink.RSId = RSName;
                db.ObjectStateManager.ChangeObjectState(machineRSLink, EntityState.Modified);
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            return View(machine);
        }

        //
        // GET: /Machine/Delete/5

        public ActionResult Delete(int id = 0)
        {
            var machineTechnicianLink = db.MachineTechnicianLinks.Single(machineTechLink => machineTechLink.MachineId == id);
            db.MachineTechnicianLinks.DeleteObject(machineTechnicianLink);
            db.SaveChanges();
            var macRSLink = db.MachineRSLinks.Single(machineRSLink => machineRSLink.MachineId == id);
            db.MachineRSLinks.DeleteObject(macRSLink);
            db.SaveChanges();
            Machine machine = db.Machines.Single(m => m.MachineId == id);
            db.Machines.DeleteObject(machine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

vendinginspection/VendingInspection/VendingInspection/Controllers/UserController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using VendingInspection.Models;
using System.Web.Script.Serialization;
using VendingInspection.ViewModels;
using WebMatrix.WebData;

namespace VendingInspection.Controllers
{
    public class UserController : Controller
    {
        private VendingCareEntities db = new VendingCareEntities();


        #region Methods and Functions related to Web Service

        


        // Login for Vending care
        [AllowAnonymous]
        [HttpGet]
        public ActionResult LoginVendingCare(string username, string password)
        {
            try
            {
                var userDetailId = db.AuthenticateUser(username, password).FirstOrDefault();
                if (ModelState.IsValid && userDetailId.HasValue && userDetailId.Value > 0)
                {
                    return Json(userDetailId.ToString(), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        // Get user details
        [HttpGet]
        public ActionResult GetUserDetails(string userDetailId)
        {
            try
            {
                UserDetail userDetail = db.GetUserDetail(Convert.ToInt64(userDetailId)).FirstOrDefault();

                if (ModelState.IsValid && userDetail != null)
                {
                    UserDetailsViewModel userDetailsViewModel = ModelToViewModel(userDetail);
                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    string result = serializer.Serialize(userDetailsViewModel);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        // Convert UserDetail to UserDetailsViewModel.
        private UserDetailsViewModel ModelToViewModel(UserDetail model)
        {
            UserDetailsViewModel viewModel = new UserDetailsViewModel();
            viewModel.UserId = model.UserId;
            viewModel.UserDetailId = model.UserDetailId;
            viewModel.CompanyId = Convert.ToInt32(model.CompanyId);
            viewModel.UserName = model.UserName;
            viewModel.Password = model.Password;
            viewModel.City = model.City;
            viewModel.State = model.State;
            viewModel.ZipCode = model.ZipCode;

            return viewModel;
        }

        #endregion

        //
        // GET: /User/

        public ActionResult Index()
        {
            var userdetails = db.UserDetails.Include("Company");
            return View(userdetails.ToList());
        }

        //
        // GET: /User/Details/5

        public ActionResult Details(long id = 0)
        {
            UserDetail userdetail = db.UserDetails.Single(u => u.UserDetailId == id);
            if (userdetail == null)
            {
                return HttpNotFound();
            }
            return View(userdetail);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            ViewBag.Roles = new SelectList(Roles.GetAllRoles());
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Create(UserDetail userdetail, string Role)
        {
            //userdetail.UserId = 0;

            if (ModelState.IsValid)
            {
                try
                {

                    if (WebSecurity.UserExists(userdetail.UserName))
                    {
                        ModelState.AddModelError("", ErrorMessges.ErrorCodeToString(MembershipCreateStatus.DuplicateUserName));
                    }
                    else
                    {
                        WebSecurity.CreateUserAndAccount(userdetail.UserName, userdetail.Password);
                        Roles.AddUserToRole(userdetail.UserName, Role);
                        int userId = WebSecurity.GetUserId(userdetail.UserName);
                        userdetail.UserId = userId;
                        userdetail.CompanyId =(Int32) Session["CompanyId"];
                        db.UserDetails.AddObject(userdetail);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("", ErrorMessges.ErrorCodeToString(e.StatusCode));
                }
                // If we got this far, something failed, redisplay form
                ViewBag.Roles = new SelectList(Roles.GetAllRoles());
                return View(userdetail);
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", userdetail.CompanyId);
            return View(userdetail);
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(long id = 0)
        {
            UserDetail userdetail = db.UserDetails.Single(u => u.UserDetailId == id);
            var roleName = Roles.GetRolesForUser(userdetail.UserName);
            ViewBag.Roles = new SelectList(Roles.GetAllRoles(), roleName[0]);
            if (userdetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", userdetail.CompanyId);
            return View(userdetail);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult Edit(UserDetail userdetail,string Role)
        {
            if (ModelState.IsValid)
            {
                var userFromDB = db.GetUserDetail(userdetail.UserDetailId).SingleOrDefault();
                userFromDB.UserName = userdetail.UserName;
                userFromDB.FirstName = userdetail.FirstName;
                userFromDB.LastName = userdetail.LastName;
                userFromDB.Address = userdetail.Address;
                userFromDB.City = userdetail.City;
                userFromDB.State = userdetail.State;
                userFromDB.ZipCode = userdetail.ZipCode;
                userFromDB.Region = userdetail.Region;
                userFromDB.ServiceProviderName = userdetail.ServiceProviderName;
                userFromDB.Designation = userdetail.Designation;
                userFromDB.Age = userdetail.Age;
                userFromDB.MobileNumber = userdetail.MobileNumber;
                if(userdetail.Password != userFromDB.Password)
                {
                    userFromDB.Password = userdetail.Password;
                    WebSecurity.ChangePassword(userFromDB.UserName, userFromDB.Password, userdetail.Password);
                }

                var roleName = Roles.GetRolesForUser(userdetail.UserName);
                if (!roleName.Contains(Role))
                {
                    Roles.RemoveUserFromRole(userdetail.UserName, roleName[0]);
                    Roles.AddUserToRole(userdetail.UserName,Role);
                }

                db.ObjectStateManager.ChangeObjectState(userFromDB, EntityState.Modified);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", userdetail.CompanyId);
            return View(userdetail);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(long id = 0)
        {
            UserDetail userdetail = db.UserDetails.Single(u => u.UserDetailId == id);
            if (userdetail == null)
            {
                return HttpNotFound();
            }
            return View(userdetail);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            UserDetail userdetail = db.UserDetails.Single(u => u.UserDetailId == id);
            db.UserDetails.DeleteObject(userdetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

vendinginspection/VendingInspection/VendingInspection/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap" style="overflow:auto;height:350px">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                
                <tbody>
                    
                    @RenderGridBody()
                    
                </tbody>
                
            </table>
        </div>
        @RenderGridPager()
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

vendinginspection/VendingInspection/VendingInspection/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager pagination">
    <ul>
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

vendinginspection/VendingInspection/VendingInspection/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Vending Care</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Machine Care", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <br />
                    <br />
                    <br />
                </div>
            </div>
        </header>
        <div id="body" >
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Span Infotech Pvt. Ltd.</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

vendinginspection/VendingInspection/VendingInspection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Vending Care</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
    <script type="text/javascript">

        $.ajaxSetup({ cache: false });

        $(document).ready(function () {
            $(".openDialog").live("click", function (e) {
                e.preventDefault();

                $("<div style ='background-color:#efeeef;'></div>")
                    .addClass("dialog")
                    .attr("id", $(this)
                    .attr("data-dialog-id"))
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        close: function () { $(this).remove(); },
                        modal: true,
                        height: $(this).attr("height"),
                        width: $(this).attr("width"),
                        left: 0

                    })
                    .load(this.href);
            });

            $(".close").live("click", function (e) {
                e.preventDefault();
                $(this).closest(".dialog").dialog("close");

            });
        });
    </script>

    <style type="text/css">
        
        #menu, #menu ul {
	list-style:none;
	padding:0;
	margin:0;
}
#menu li {
	float:left;
	position:relative;
	line-height: 2.5em;
	width: 8em;
}

#menu li ul li {
	float:left;
	position:relative;
	line-height: 2.5em;
	width: 12em;
}

        
        #menu li ul {
	position:absolute;
	margin-top:-0.5em;
	margin-left:.15em;
	display:none;
}
#menu ul li ul {
	margin-top:-3.5em;
	margin-left:3em;
	text-align:left;
	width:15em;
	
	
}
        
      

#menu a {
	display:inline;
	border-right:1px solid #fff;
	background:Yellow;
	color:#3B3B3B;
	text-decoration:none;
	padding:0 10px;
	margin-top:0px;
	width:100px;
	height:30px;
}
#menu a:hover {
	background-color:Yellow;
	color:#fff;
}
#menu ul {
	border-top:1px solid #fff;
}
#menu ul a {
	background:Yellow;
	height:30px;
}

/* SHOW SUBMENU 1 */
#menu li:hover ul, #menu li.over ul {
	display:block;
}
#menu li:hover ul ul, #menu li.over ul ul {
	display:none;
}
/* SHOW SUBMENU 2 */
#menu ul li:hover ul, #menu ul li.over ul {
	display:block;
}

    </style>

</head>
<body>
    <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Machine Care", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Dashboard", "Home")</li>
                            <li>@Html.ActionLink("RouteCause", "Index", "RouteCause")</li>
                            <li>@Html.ActionLink("Users", "Index", "User")</li>
                            <li>@Html.ActionLink("Jobs", "Index", "Job")</li>
                            <li>@Html.ActionLink("Machines", "Index", "Machine")</li>
                             <li>@Html.ActionLink("Inventory", "Index", "InventoryItem")</li>
                             <li>@Html.ActionLink("Permissions", "Index", "Group")</li>
                             <li>@Html.ActionLink("Reports", "", "")
                             <ul style="background-color:Lime">
			            <li style="background-color:Yellow;height:30px">@Html.ActionLink("PM Report", "GetJobReport", "Report", new { jobTypeId = 1 }, null)</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("BM", "GetJobReport", "Report", new { jobTypeId = 2 }, null)</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("PDI", "GetJobReport", "Report", new { jobTypeId = 3 }, null)</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("Ins", "GetJobReport", "Report", new { jobTypeId = 4 }, null)</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("RS Wise", "GetRSWiseReport", "Report")</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("Model Wise", "GetModelWiseReport", "Report")</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("Spares Consum.", "GetSparesConsumption", "Report")</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("Category Wise", "GetCategoryWise", "Report")</li>
                             <li style="background-color:Yellow;margin-top:1px;height:30px">@Html.ActionLink("Inactive Machines", "GetMachines", "Report", new { Status="InActive"},null)</li>

                </ul>
                             </li>

                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
           @Html.Raw(@ViewBag.Message)  
            @RenderBody()
        </section>
    </div>
    <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Span Infotech Pvt. Ltd.</p>
                </div>
            </div>
        </footer>
    @RenderSection("scripts", required: false)
</body>
</html>