vendinginspection/VendingInspection/VendingInspection/Controllers/UserInventoryItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VendingInspection.Models;

namespace VendingInspection.Controllers
{
    public class UserInventoryItemController : Controller
    {
        private VendingCareEntities db = new VendingCareEntities();

        //
        // GET: /UserInventoryItem/

        public ActionResult Index(long id = 0)
        {
            ViewBag.Message = TempData["Message"];
            IEnumerable<UserInventoryItemsForUserId> list = null;
            if (id > 0)
            {
                var userinventoryitems = db.GetUserInventoryItems(id);
                    //db.UserInventoryItems.Include("InventoryItem").Include("UserDetail");
                list = userinventoryitems.ToList();
            }
            return View(list);
        }

        //
        // GET: /UserInventoryItem/Details/5

        public ActionResult Details(long id = 0)
        {
            UserInventoryItem userinventoryitem = db.UserInventoryItems.Single(u => u.UserInventoryItemId == id);
            if (userinventoryitem == null)
            {
                return HttpNotFound();
            }
            return View(userinventoryitem);
        }

        //
        // GET: /UserInventoryItem/Create

        public ActionResult Create()
        {
            ViewBag.ItemId = new SelectList(db.InventoryItems, "ItemId", "ItemName");
            ViewBag.UserDetailId = new SelectList(db.UserDetails, "UserDetailId", "UserName");
            return View();
        }

        //
        // POST: /UserInventoryItem/Create

        [HttpPost]
        public ActionResult Create(UserInventoryItem userinventoryitem)
        {
            if (ModelState.IsValid)
            {
                db.UserInventoryItems.AddObject(userinventoryitem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ItemId = new SelectList(db.InventoryItems, "ItemId", "ItemName", userinventoryitem.ItemId);
            ViewBag.UserDetailId = new SelectList(db.UserDetails, "UserDetailId", "UserName", userinventoryitem.UserDetailId);
            return View(userinventoryitem);
        }

        //
        // GET: /UserInventoryItem/Edit/5

        public ActionResult Edit(long userid = 0, long itemId = 0)
        {
            /*UserInventoryItem userinventoryitem = db.UserInventoryItems.Single(u => u.UserInventoryItemId == id);
            if (userinventoryitem == null)
            {
                return HttpNotFound();
            }
            ViewBag.ItemId = new SelectList(db.InventoryItems, "ItemId", "ItemName", userinventoryitem.ItemId);
            ViewBag.UserDetailId = new SelectList(db.UserDetails, "UserDetailId", "UserName", userinventoryitem.UserDetailId);
            return View(userinventoryitem);*/

            var userinventoryitems = db.GetUserInventoryItems(userid).ToList();
            UserInventoryItemsForUserId userInventoryItemsForUserId = userinventoryitems.FirstOrDefault(n => n.ItemId == itemId);
            return View(userInventoryItemsForUserId);
        }

        //
        // POST: /UserInventoryItem/Edit/5

        [HttpPost]
        public ActionResult Edit(UserInventoryItemsForUserId userInventoryItemsForUserId)
        {
            if (userInventoryItemsForUserId.UserDetailId != null)
            {
                UserInventoryItem userinventoryitem = new UserInventoryItem()
                                                          {
                                                              ItemId = userInventoryItemsForUserId.ItemId,
                                                              UserDetailId =
                                                                  (long)userInventoryItemsForUserId.UserDetailId,
                                                              UserInventoryItemId =
                                                                  userInventoryItemsForUserId.UserInventoryItemId,
                                                              Quantity = userInventoryItemsForUserId.Quantity,
                                                          };
                if (ModelState.IsValid)
                {
                    if (userinventoryitem.UserInventoryItemId > 0)
                    {
                        db.UserInventoryItems.Attach(userinventoryitem);
                        db.ObjectStateManager.ChangeObjectState(userinventoryitem, EntityState.Modified);
                        db.SaveChanges();

                    }
                    else
                    {
                        db.UserInventoryItems.AddObject(userinventoryitem);
                        db.SaveChanges();
                    }
                    TempData["Message"] = CommanUtility.GetMessage(CommanUtility.ErrorType.Information, "Record Updated");
                    return RedirectToAction("Index", new { id = userInventoryItemsForUserId.UserDetailId });
                }
                /*ViewBag.ItemId = new SelectList(db.InventoryItems, "ItemId", "ItemName", userinventoryitem.ItemId);
                ViewBag.UserDetailId = new SelectList(db.UserDetails, "UserDetailId", "UserName", userinventoryitem.UserDetailId);
                return View(userinventoryitem);*/
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /UserInventoryItem/Delete/5

        public ActionResult Delete(long id = 0)
        {
            UserInventoryItem userinventoryitem = db.UserInventoryItems.Single(u => u.UserInventoryItemId == id);
            if (userinventoryitem == null)
            {
                return HttpNotFound();
            }
            return View(userinventoryitem);
        }

        //
        // POST: /UserInventoryItem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            UserInventoryItem userinventoryitem = db.UserInventoryItems.Single(u => u.UserInventoryItemId == id);
            db.UserInventoryItems.DeleteObject(userinventoryitem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

vendinginspection/VendingInspection/VendingInspection/Views/UserInventoryItem/Create.cshtml
@model VendingInspection.Models.UserInventoryItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserInventoryItem</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserDetailId, "UserDetail")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserDetailId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserDetailId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemId, "InventoryItem")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ItemId", String.Empty)
            @Html.ValidationMessageFor(model => model.ItemId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

vendinginspection/VendingInspection/VendingInspection/Views/UserInventoryItem/Delete.cshtml
@model VendingInspection.Models.UserInventoryItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>UserInventoryItem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserDetail.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserDetail.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InventoryItem.ItemName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InventoryItem.ItemName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

vendinginspection/VendingInspection/VendingInspection/Views/UserInventoryItem/Details.cshtml
@model VendingInspection.Models.UserInventoryItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>UserInventoryItem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserDetail.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserDetail.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InventoryItem.ItemName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InventoryItem.ItemName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.UserInventoryItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

vendinginspection/VendingInspection/VendingInspection/Views/UserInventoryItem/Edit.cshtml
@model VendingInspection.Models.UserInventoryItemsForUserId
@{
    ViewBag.Title = "Edit";
    Layout = null;
}
<h2>
    Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ItemId)
    @Html.HiddenFor(model => model.UserDetailId)
    @Html.HiddenFor(model => model.UserInventoryItemId)
        
   
    <div style="clear: both; height: 10px">
    </div>
@*<div>
        <div class="form_leftColumn">
            @Html.LabelFor(model => model.ItemName, "Item Name")
        </div>
        <div class="form_rightColumn">
            @Html.LabelFor(model => model.ItemName, Model.ItemName)
        </div>
    </div>
    <div>
        <div class="form_leftColumn">
            @Html.LabelFor(model => model.Quantity)
        </div>
        <div class="form_rightColumn">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>
    </div>*@
    <div class="div-editor-label">
        @Html.LabelFor(model => model.ItemName, "Item Name")
    </div>
    <div class="div-editor-field">
        @Html.LabelFor(model => model.ItemName, Model.ItemName)
    </div>
    <div class="div-editor-label">
        @Html.LabelFor(model => model.Quantity)
    </div>
    <div class="div-editor-field">
        @Html.EditorFor(model => model.Quantity)
        @Html.ValidationMessageFor(model => model.Quantity)
    </div>
    <p>
        <input type="submit" value="Save" />
    </p>
   
}
<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.UserDetailId })
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

vendinginspection/VendingInspection/VendingInspection/Views/UserInventoryItem/Index.cshtml
@using GridMvc.Html
@model IEnumerable<VendingInspection.Models.UserInventoryItemsForUserId>
@{
    ViewBag.Title = "Manage Users InventoryItems";
}
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
<div style="height: 490px">
    <div style="height: 50px;">
        <h2>
            Manage Users InventoryItems</h2>
    </div>
    <div style="height: 440px;">
        <div style="height: 400px; vertical-align: top">
            @if (Model != null)
            {@Html.Grid(Model).Columns(columns =>
                                          {

                                              columns.Add(c => c.ItemName).Titled("Item Name");
                                              columns.Add(c => c.Quantity).Titled("Quantity");
                                              columns.Add()
                                                  .Titled("Action")
                                                  .Sanitized(false)
                                                  .Encoded(false)
                                                  .RenderValueAs(o => Html.ActionLink("Edit", "Edit", "UserInventoryItem", new { userid = o.UserDetailId, itemId = o.ItemId }, new { @class = "openDialog", data_dialog_id = "aboutlDialog", data_dialog_title = "User InventoryItems", height = 320, width = 600 }));

                                          }).WithPaging(200).Sortable(true)}
        </div>
    </div>
</div>
@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
              $1$  @Html.ActionLink("Edit", "Edit", new { id = item.UserInventoryItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.UserInventoryItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserInventoryItemId })#1#
                @Html.ActionLink("Edit", "Edit", "UserInventoryItem", new { userid = item.UserDetailId, itemId = item.ItemId }, new { @class = "openDialog", data_dialog_id = "aboutlDialog", data_dialog_title = "About Us" })
            </td>
        </tr>
    }
</table>*@ 