vendinginspection/VendingInspection/VendingInspection/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VendingInspection.Models;
using VendingInspection.ViewModels;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;


namespace VendingInspection.Controllers
{
    public class JobController : Controller
    {
        private VendingCareEntities db = new VendingCareEntities();

        #region Methods and Functions related to Web Service
        // Get user jobs
        [HttpGet]
        public ActionResult GetUserJobs(string userDetailId)
        {
            try
            {
                List<UserJobInformation> userJobInformation = db.GetUserJobs(Convert.ToInt64(userDetailId)).ToList();
                List<UserJobInformationViewModel> userDetailsViewModel = new List<UserJobInformationViewModel>();
                if (ModelState.IsValid && userJobInformation != null)
                {
                    userJobInformation.ForEach(jobInformation =>
                        {
                            userDetailsViewModel.Add(ModelToViewModel(jobInformation));

                        });

                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    string result = serializer.Serialize(userDetailsViewModel);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        [HttpPost]
        public ActionResult SetJobStartTime(string value)
        {
            try
            {
                var data = (JObject)JsonConvert.DeserializeObject(value);
                //Set job finish time
                var jobId = data["jobId"].ToObject<Int64>();
                var currentLocation = data["currentLocation"].ToObject<String>();
                Job job = db.Jobs.Single(j => j.JobId == jobId);
                job.JobStartDate = DateTime.Now;
                job.JobStartLocation = currentLocation;
                db.ObjectStateManager.ChangeObjectState(job, EntityState.Modified);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                return Json(ex.InnerException.Message, JsonRequestBehavior.AllowGet);
            }

            return Json("Ok", JsonRequestBehavior.AllowGet);
        }

        // Convert UserJobInformation to UserJobInformationViewModel.
        private UserJobInformationViewModel ModelToViewModel(UserJobInformation model)
        {
            UserJobInformationViewModel viewModel = new UserJobInformationViewModel();
            viewModel.JobId = model.JobId;
            viewModel.JobTypeId = model.JobTypeId;
            viewModel.BarCode = model.BarCode;
            viewModel.CustomerName = model.CustomerName;
            viewModel.CustomerAddress = model.CustomerAddress;
            viewModel.ContactPerson = model.ContactPerson;
            viewModel.ContactNumber = model.ContactNumber;
            viewModel.MachineLocation = model.MachineLocation;
            viewModel.Lane = model.Lane;
            viewModel.Model = model.Model;
            viewModel.AcOrDc = model.AcOrDc;
            viewModel.WaterSource = model.WaterSource;
            viewModel.ManufacturerName = model.ManufacturerName;
            viewModel.ManufacturerYear = model.ManufacturerYear;
            viewModel.Branding = model.Branding;
            return viewModel;
        }
        #endregion
        //
        // GET: /Job/

        public ActionResult Index()
        {
            List<JobInformation> jobs = db.GetAllJobs().ToList<JobInformation>();
            return View(jobs.ToList());
        }

        //
        // GET: /Job/Details/5

        public ActionResult Details(long id = 0)
        {
            var job = db.GetAllJobs().Where(j => j.JobId == id).SingleOrDefault();
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        //
        // GET: /Job/Create

        public ActionResult Create()
        {
            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(), "UserId", "FirstName");
            ViewBag.CallCategories = new SelectList(db.ComplaintCategories, "ComplaintCategoryId","ComplaintCategory1");
            ViewBag.JobTypes = new SelectList(db.JobTypes.Where(c => c.JobTypeId != 3 && c.JobTypeId != 5), "JobTypeId", "Description");
            return View();
        }

        //
        // POST: /Job/Create

        [HttpPost]
        public ActionResult Create(Job job)
        {
            if (ModelState.IsValid)
            {
                job.CompanyId = (Int32)Session["CompanyId"];
                job.JobCreationDate = DateTime.Now;
                job.Status = 0;
                db.Jobs.AddObject(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", job.CompanyId);
            return View(job);
        }

        //
        // GET: /Job/Edit/5

        public ActionResult Edit(long id = 0)
        {
            Job job = db.Jobs.Single(j => j.JobId == id);
            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(), "UserId", "FirstName", job.Technician);
            ViewBag.CallCategories = new SelectList(db.ComplaintCategories, "ComplaintCategoryId", "ComplaintCategory1");
            ViewBag.JobTypes = new SelectList(db.JobTypes.Where(c => c.JobTypeId != 3 && c.JobTypeId != 5), "JobTypeId", "Description",job.JobTypeId);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(), "UserId", "FirstName");
            return View(job);
        }

        //
        // POST: /Job/Edit/5

        [HttpPost]
        public ActionResult Edit(Job job)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var jobToUpdate = db.Jobs.SingleOrDefault(j => j.JobId == job.JobId);
                    jobToUpdate.Technician = job.Technician;
                    jobToUpdate.JobTypeId = job.JobTypeId;
                    jobToUpdate.RegisteredByName = job.RegisteredByName;
                    jobToUpdate.RegisteredByNumber = job.RegisteredByNumber;
                    jobToUpdate.CallCategory = job.CallCategory;
                    db.ObjectStateManager.ChangeObjectState(jobToUpdate, EntityState.Modified);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                HandleErrorInfo errorInfo = new HandleErrorInfo(ex, "Job", "Edit");
                return View(job);
            }
            ViewBag.Technicians = new SelectList(db.GetAllTechnicians(), "UserId", "FirstName");
            return View(job);
        }

        //
        // GET: /Job/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Job job = db.Jobs.Single(j => j.JobId == id);
            db.Jobs.DeleteObject(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

vendinginspection/VendingInspection/VendingInspection/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VendingInspection.Models;
using VendingInspection.ViewModels;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace VendingInspection.Controllers
{
    public class WorkOrderController : Controller
    {
        private VendingCareEntities db = new VendingCareEntities();

        #region Method and Functions related to web service
        // Get work order parameters.
        [HttpGet]
        public ActionResult GetWorkOrderParameters()
        {
            try
            {
                List<WorkOrderParameter> workOrderParams = db.GetWorkOrderParameters().ToList();
                List<WorkOrderParameterViewModel> workOrderParameters = new List<WorkOrderParameterViewModel>();
                if (ModelState.IsValid && workOrderParams != null)
                {
                    workOrderParams.ForEach(workOrderParameter =>
                        {
                            workOrderParameters.Add(ModelToViewModel(workOrderParameter));
                        });

                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    string result = serializer.Serialize(workOrderParameters);

                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(ex, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        // Save work order.
        [HttpPost]
        public ActionResult SaveWorkOrder(string value)
        {
            try
            {
                var data = (JObject)JsonConvert.DeserializeObject(value);
                Job objJob = null;
                var workOrderDetail = data["WorkOrderDetail"].ToObject<WorkOrderDetailViewModel>();

                if (workOrderDetail.JobId > 0)
                {
                    objJob = db.Jobs.Single(j => j.JobId == workOrderDetail.JobId);
                    objJob.JobFinishDate = DateTime.Now;
                    objJob.Status = 1;
                    objJob.JobEndLocation = workOrderDetail.JobEndLocation;
                    objJob.Remarks = workOrderDetail.Remarks;
                    objJob.CustomerSignature = Convert.FromBase64String(workOrderDetail.Signature);
                    objJob.CustomerContactNo = workOrderDetail.ContactNo;
                    db.ObjectStateManager.ChangeObjectState(objJob, EntityState.Modified);
                    db.SaveChanges();

                    //Save work order parameter details
                    SaveWorkOrderParameters(workOrderDetail, objJob.JobId);

                    //Save spare part details
                    SaveWorkOrderSpareDetails(workOrderDetail, objJob.JobId);

                    //Save ingredient details
                    SaveWorkOrderIngredientDetails(workOrderDetail, objJob.JobId);

                    //Save job pictures
                    SaveWorkOrderPictures(workOrderDetail, objJob.JobId);

                    //Save Complaint Detail
                    SaveComplaintDetail(workOrderDetail, objJob.JobId);
                }
                else
                {
                    objJob = new Job();
                    objJob.CompanyId = workOrderDetail.CompanyId;
                    objJob.BarCode = workOrderDetail.BarCode;
                    objJob.JobCreationDate = DateTime.Now;
                    objJob.JobStartDate = (DateTime)workOrderDetail.JobStartDateTime;
                    objJob.JobFinishDate = DateTime.Now;
                    objJob.Status = 1;
                    objJob.Technician = workOrderDetail.TechnicianId;
                    objJob.JobTypeId = workOrderDetail.JobTypeId;
                    objJob.JobStartLocation = workOrderDetail.JobStartLocation;
                    objJob.JobEndLocation = workOrderDetail.JobEndLocation;
                    objJob.CustomerSignature = Convert.FromBase64String(workOrderDetail.Signature);
                    objJob.CustomerContactNo = workOrderDetail.ContactNo;
                    objJob.Remarks = workOrderDetail.Remarks;

                    db.Jobs.AddObject(objJob);
                    db.SaveChanges();

                    //Save pdi details
                    SavePdiDetail(workOrderDetail, objJob.JobId);

                    //Save spare part details
                    SaveWorkOrderSpareDetails(workOrderDetail, objJob.JobId);
                }

                

                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.InnerException.Message, JsonRequestBehavior.AllowGet);
            }

            //return Json("Ok", JsonRequestBehavior.AllowGet);
        }

        private void SavePdiDetail(WorkOrderDetailViewModel workOrderDetail, Int64 jobId)
        {
            var PdiDetail = new PDIDetail();
            
                if (ModelState.IsValid)
                {
                    PdiDetail.JobId = jobId;
                    PdiDetail.BarCode = workOrderDetail.BarCode;
                    PdiDetail.RSId = workOrderDetail.RSId;
                    PdiDetail.Lane = workOrderDetail.Lane;
                    PdiDetail.Model = workOrderDetail.Model;
                    PdiDetail.AcOrDc = workOrderDetail.AcOrDc;
                    PdiDetail.WaterSource = workOrderDetail.WaterSource;
                    PdiDetail.ManufecturerName = workOrderDetail.ManufecturerName;
                    PdiDetail.ManufacturerYear = workOrderDetail.ManufecturerYear;
                    PdiDetail.Branding = workOrderDetail.Branding;
                    PdiDetail.OverAllBodyCondition = workOrderDetail.OverAllBodyCondition;
                    db.PDIDetails.AddObject(PdiDetail);
                    db.SaveChanges();
                }
        }
       
        private void SaveComplaintDetail(WorkOrderDetailViewModel workOrderDetail, Int64 jobId)
        {
            List<ComplaintDetailViewModel> complaintList = workOrderDetail.ComplaintDetail;
            if (complaintList != null && complaintList.Count > 0)
            {
                if (ModelState.IsValid)
                {
                    complaintList.ForEach(complaint =>
                    {
                        var jobComplaint = new JobComplaint();
                        jobComplaint.JobId = jobId;
                        jobComplaint.ComplaintCategoryId = complaint.ComplaintCategoryId;
                        jobComplaint.RouteCauseId = complaint.RouteCauseId;
                        db.JobComplaints.AddObject(jobComplaint);
                    });

                    db.SaveChanges();
                }
            }
        }

        private void SaveWorkOrderParameters(WorkOrderDetailViewModel workOrderDetail, Int64 jobId)
        {
            List<WorkOrder> workOrderParameterList = workOrderDetail.WorkOrderParameterDetail;
            if (workOrderParameterList != null && workOrderParameterList.Count > 0)
            {
                if (ModelState.IsValid)
                {
                    workOrderParameterList.ForEach(workOrder =>
                    {
                        if (workOrderDetail.JobId == 0)
                            workOrder.JobId = jobId;
                        db.WorkOrders.AddObject(workOrder);
                    });

                    db.SaveChanges();
                }
            }
        }

        private void SaveWorkOrderSpareDetails(WorkOrderDetailViewModel workOrderDetail, Int64 jobId)
        {
            if (workOrderDetail.IsSparePartsUsed)
            {
                if (workOrderDetail.SparePartUsed != null && workOrderDetail.SparePartUsed.Count > 0)
                {
                    var SparePartList = workOrderDetail.SparePartUsed;
                    SparePartList.ForEach(sparePart =>
                    {
                        var sparePartUsed = new JobInventoryItem()
                        {
                            JobId = jobId,
                            InventoryItemId = sparePart.ItemId,
                            Quantity = sparePart.Quantity,
                        };

                        db.JobInventoryItems.AddObject(sparePartUsed);
                    });

                    db.SaveChanges();
                }
            }
        }

        private void SaveWorkOrderIngredientDetails(WorkOrderDetailViewModel workOrderDetail, Int64 jobId)
        {
            var ingredientList = workOrderDetail.IngredientDetail;
            if (ingredientList.Count > 0)
            {
                ingredientList.ForEach(ingredient =>
                {
                    var ingredientDetail = new JobIngredient()
                    {
                        JobId = jobId,
                        IngredientId = ingredient.IngredientId,
                        Water = ingredient.Water,
                        Premix = ingredient.Premix,
                        Temp = ingredient.Temp,
                        Counter = ingredient.Counter
                    };

                    db.JobIngredients.AddObject(ingredientDetail);
                });
                db.SaveChanges();
            }
            
        }

        private void SaveWorkOrderPictures(WorkOrderDetailViewModel workOrderDetail,Int64 jobId)
        {
            var pictures = workOrderDetail.Pictures;
            if (workOrderDetail.Pictures != null && workOrderDetail.Pictures.Count > 0)
            {
                pictures.ForEach(picture =>
                {
                    var pictureEntry = new JobImage()
                    {
                        JobId = jobId,
                        Image = Convert.FromBase64String(picture)
                    };

                    db.JobImages.AddObject(pictureEntry);

vendinginspection/VendingInspection/VendingInspection/Views/Job/Create.cshtml
@model VendingInspection.Models.Job
@{
    ViewBag.Title = "Create";
}
<script type="text/javascript">

    function GetBarCodeDetails() {

        var barcode = $("#BarCode").val()
        $.ajax({
            url: '/vendingcare/Machine/GetMachineDetailsFromBarcode',
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({ barcode: barcode }),
            success: function (data) {
                var obj = jQuery.parseJSON(data);
                if (obj.InternalId != null)
                    $("#divInterId").html(obj.InternalId);

                if (obj.CustomerID != null)
                    $("#divCustomerId").html(obj.CustomerID);

                if (obj.CustomerName != null)
                    $("#divCustomerName").html(obj.CustomerName);

                if (obj.CustomerAddress != null)
                    $("#divCustomerAddress").html(obj.CustomerAddress);
                if (obj.AreaCode != null)
                    $("#divAreaCode").html(obj.AreaCode);
                if (obj.City != null)
                    $("#divCity").html(obj.City);
                if (obj.State != null)
                    $("#divState").html(obj.State);
                if (obj.PinCode != null)
                    $("#divPinCode").html(obj.PinCode);
                if (obj.IsActive != null)
                    $("#divIsActive").html(obj.IsActive);
                if (obj.CustomerID != null)
                    $("#divMachineLocation").html(obj.MachineLocation);
                if (obj.ContactPerson != null)
                    $("#divContactPerson").html(obj.ContactPerson);
                if (obj.ContactNumber != null)
                    $("#divContactNumber").html(obj.ContactNumber);
                if (obj.NumberOfMachine != null)
                    $("#divNumberOfMachine").html(obj.NumberOfMachine);
                if (obj.MachineStatus != null)
                    $("#divMachineStatus").html(obj.MachineStatus);
                if (obj.Category != null)
                    $("#divCategory").html(obj.Category);
                if (obj.TypeOfAccount != null)
                    $("#divTypeOfAccount").html(obj.TypeOfAccount);
                if (obj.ClassOfAccount != null)
                    $("#divClassOfAccount").html(obj.ClassOfAccount);
                if (obj.Lane != null)
                    $("#divLane").html(obj.Lane);
                if (obj.Model != null)
                    $("#divModel").html(obj.Model);
                if (obj.AcOrDc != null)
                    $("#divAcOrDc").html(obj.AcOrDc);
                if (obj.WaterSource != null)
                    $("#divWaterSource").html(obj.WaterSource);

                if (obj.ManufacturerName != null)
                    $("#divManufacturerName").html(obj.ManufacturerName);
                if (obj.ManufacturerYear != null)
                    $("#divManufacturerYear").html(obj.ManufacturerYear);

                if (obj.Branding != null)
                    $("#divBranding").html(obj.Branding);
                if (obj.TechnicianName != null)
                    $("#divTechnicianName").html(obj.TechnicianName);
                if (obj.Remarks != null)
                    $("#divRemarks").html(obj.Remarks);

            }
        });
    }
</script>
<h2>
    Create New Job</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    
    
    <div style="clear: both; height: 10px">
    </div>
    <div class="div-editor-label">
        @Html.LabelFor(model => model.BarCode)
    </div>
    <div class="div-editor-field">
        <div style="float: left;">
            @Html.EditorFor(model => model.BarCode, new { style = "width: 100px;" })
            @Html.ValidationMessageFor(model => model.BarCode)
        </div>
        <div style="float: left;">
            <img src="~/Images/search_icon.png" title="Search Barcode" alt="findbarcode" style="margin-left: 5px;
                margin-top: 5px; height: 25px" onclick="GetBarCodeDetails()" /></div>
    </div>
    <div style="clear: both; height: 10px">
    </div>
    <div class="div-editor-label">
        @Html.LabelFor(model => model.Technician)
    </div>
    <div class="div-editor-field">
        @Html.DropDownListFor(Model => Model.Technician, (IEnumerable<SelectListItem>)ViewBag.Technicians, "Select Technician")
    </div>
    <div style="clear: both; height: 10px">
    </div>
    <div class="div-editor-label">
        @Html.LabelFor(model => model.JobType)
    </div>
    <div class="div-editor-field">
        @Html.DropDownListFor(Model => Model.JobTypeId, (IEnumerable<SelectListItem>)ViewBag.JobTypes, "Select JobType")
    </div>
    
    <div class="div-editor-label">
        @Html.LabelFor(model => model.CallCategory)
    </div>
    <div class="div-editor-field">
        @Html.DropDownListFor(Model => Model.CallCategory, (IEnumerable<SelectListItem>)ViewBag.CallCategories, "Select Category")
    </div>
    
    
    <div class="div-editor-label">
        @Html.Label("Complaint Registered By")
    </div>
    <div class="div-editor-field">
        @Html.EditorFor(model => model.RegisteredByName)
        
    </div>
    <div class="div-editor-label">
        @Html.Label("Complaint Registered By Number")
    </div>
    <div class="div-editor-field">
        @Html.EditorFor(model => model.RegisteredByNumber)
    </div>
    <div style="float: left; width: 400px">
        <div class="div-editor-label">
            @Html.Label("Internal Id")
        </div>
        <div class="div-editor-field" id="divInterId">
        </div>
        <div class="div-editor-label">
            @Html.Label("Customer Id")
        </div>
        <div class="div-editor-field" id="divCustomerId">
        </div>
        <div class="div-editor-label">
            @Html.Label("Customer Name")
        </div>
        <div class="div-editor-field" id="divCustomerName">
        </div>
        <div class="div-editor-label">
            @Html.Label("Csustomer Address")
        </div>
        <div class="div-editor-field" id="divCustomerAddress">
        </div>
        <div class="div-editor-label">
            @Html.Label("AreaCode")
        </div>
        <div class="div-editor-field" id="divAreaCode">
        </div>
        <div class="div-editor-label">
            @Html.Label("City")
        </div>
        <div class="div-editor-field" id="divCity">
        </div>
        <div class="div-editor-label">
            @Html.Label("State")
        </div>
        <div class="div-editor-field" id="divState">
        </div>
        <div class="div-editor-label">
            @Html.Label("PinCode")
        </div>
        <div class="div-editor-field" id="divPinCode">
        </div>
        <div class="div-editor-label">
            @Html.Label("IsActive")
        </div>
        <div class="div-editor-field" id="divIsActive">
        </div>
        <div class="div-editor-label">
            @Html.Label("MachineLocation")
        </div>
        <div class="div-editor-field" id="divMachineLocation">
        </div>
        <div class="div-editor-label">
            @Html.Label("ContactPerson")
        </div>
        <div class="div-editor-field" id="ContactPerson">
        </div>
        <div class="div-editor-label">
            @Html.Label("ContactNumber")
        </div>
        <div class="div-editor-field" id="divContactNumber">
        </div>
        <div class="div-editor-label">
            @Html.Label("Number Of Machine")
        </div>
        <div class="div-editor-field" id="divNumberOfMachine">
        </div>
    </div>
    <div style="float: left; width: 400px; margin-left: 50px">
        <div class="div-editor-label">
            @Html.Label("MachineStatus")
        </div>
        <div class="div-editor-field" id="divMachineStatus">
        </div>
        <div class="div-editor-label">
            @Html.Label("Category")
        </div>
        <div class="div-editor-field" id="divCategory">
        </div>
        <div class="div-editor-label">
            @Html.Label("TypeOfAccount")
        </div>
        <div class="div-editor-field" id="divTypeOfAccount">
        </div>
        <div class="div-editor-label">
            @Html.Label("ClassOfAccount")
        </div>
        <div class="div-editor-field" id="divClassOfAccount">
        </div>
        <div class="div-editor-label">
            @Html.Label("Lane")
        </div>
        <div class="div-editor-field" id="divLane">
        </div>
        <div class="div-editor-label">
            @Html.Label("Model")
        </div>
        <div class="div-editor-field" id="divModel">
        </div>
        <div class="div-editor-label">
            @Html.Label("AcOrDc")
        </div>
        <div class="div-editor-field" id="divAcOrDc">
        </div>
        <div class="div-editor-label">
            @Html.Label("WaterSource")
        </div>
        <div class="div-editor-field" id="divWaterSource">
        </div>
        <div class="div-editor-label">
            @Html.Label("ManufacturerName")
        </div>
        <div class="div-editor-field" id="divManufacturerName">
        </div>
        <div class="div-editor-label">
            @Html.Label("ManufacturerYear")
        </div>
        <div class="div-editor-field" id="divManufacturerYear">
        </div>
        <div class="div-editor-label">
            @Html.Label("Branding")
        </div>
        <div class="div-editor-field" id="divBranding">
        </div>
        <div class="div-editor-label">
            @Html.Label("Remarks")
        </div>
        <div class="div-editor-field" id="divRemarks">
        </div>
    </div>
    <div style="clear: both; height: 10px">
    </div>
  
    <div style="clear: both; height: 20px">
    </div>
    <p>
        <input type="submit" value="Create" />
    </p>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

vendinginspection/VendingInspection/VendingInspection/Views/Job/Index.cshtml
@model IEnumerable<VendingInspection.Models.JobInformation>
@using GridMvc.Html
@{
    ViewBag.Title = "Manage Jobs";
}
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
<script>
    function CheckJobCompletion(jobStatus)
    {
        if (!jobStatus) { 
            alert("Work order detail not available, as job is yet not completed.")
            return false;
        }
    }
</script>
<div style="height: 490px">
    <div style="height: 50px;">
        <h2>
            Manage Jobs</h2>
    </div>
    <div style="height: 440px;">
        <div style="height: 40px;">
            <span id="id_0" class="button_example" style="cursor: pointer;">
                @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "Button" })
            </span>
        </div>
        <div style="height: 400px; vertical-align: top;">
            @Html.Grid(Model).Columns(columns =>
       {
           columns.Add(c => c.Type).Titled("Type").SetWidth(50);
           columns.Add(c => c.RegisteredByName).Titled("Call Reg. By").SetWidth(50);
           columns.Add(c => c.RegisteredByNumber).Titled("Call Reg. No.").SetWidth(50);
           columns.Add(c => c.CallCategory).Titled("Call Category").SetWidth(50);
           columns.Add(c => c.CustomerName).Titled("Acc. Name").SetWidth(50);
           columns.Add(c => c.BarCode).Titled("BarCode").SetWidth(50);
           columns.Add(c => c.Technician).Titled("Tech.").SetWidth(50);
           columns.Add(c => c.jobcreationdate).Titled("Created On").SetWidth(80);
           columns.Add(c => c.jobstartdate).Titled("Started On").SetWidth(70);
           columns.Add(c => c.jobfinishdate).Titled("Finished on").SetWidth(80);
           columns.Add(c => c.CustomerAddress).Titled("Address").SetWidth(200);
           columns.Add(c => c.Status).Titled("Status").SetWidth(50);

           columns.Add()
                                .Titled("Action")
                                .Sanitized(false)
                                .Encoded(false)
                                .RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Job", new { Id = c.JobId }, new { @style = c.Status == "Finished" ? "display:none" : "display:inline" }).ToHtmlString() + Html.ActionLink("|" + " Delete", "Delete", "Job", new { Id = c.JobId }, new { onclick = "return confirm('Are you sure you want to delete this job?')", @style = c.Status == "Finished" ? "display:none" : "display:inline" }).ToHtmlString() + "|" + Html.ActionLink("Details", "Details", "Job", new { Id = c.JobId }, null).ToHtmlString() + Html.ActionLink("|" + " WorkOrder", "Details", "WorkOrder", new { Id = c.JobId, JobTypeId = c.JobTypeId }, new { onclick = "return CheckJobCompletion('" + c.Status + "');", @style = c.Status == "Finished" ? "display:inline" : "display:none" }).ToHtmlString()).SetWidth(200);
       }).WithPaging(50).Sortable(true)
        </div>
    </div>
</div>